### ISSUE TITLE
Adding a Contribution Guide

### ISSUE THREAD

**Issue by Clozent** [avitran0/btd6-stats#1]
Hello, I would like to help work on the project, mainly by adding data, but there is no contribution guide.
I might be able to infer the data's structure from the json files, but I want to be sure about the details before I put time down for this.

**Comment by avitran0** [comment]
i can do that when i have the time to, at the moment i'm not really working on the site.

**Comment by Clozent** [comment]
Unrelated to the issue, but just so you know, the site's server is down.
